# Generated by Django 4.0.4 on 2022-05-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placementbid',
            options={'ordering': ['-placementbid_modified']},
        ),
    ]
